M48
; DRILL file KiCad 10.0.3 date 2026-07-09T23:47:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-09T23:47:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X53.5Y-121.0
T2
X64.8Y-109.05
X64.8Y-132.05
X122.8Y-109.05
X122.8Y-132.05
T3
X53.5Y-75.0
X53.5Y-113.0
X179.5Y-71.0
X179.5Y-122.228
M30
